### ISSUE TITLE
Communicator tab testing

### ISSUE THREAD

**Issue by jpaquete** [v-bodnar/ocpp-server#1]
I am testing this program, I could not figure out how to receive messages from ocpp simulators, nor how to use the communicator tab. It says Selected client and I cant type anything, when I clieck send message it says "Client to send for is not selected"... Can you please explain and elaborate a littlel more on the documentation ? Thanks a lot. It seems like a great program:)

**Comment by v-bodnar** [comment]
Hi. Glad that my work appeared handy to you. As soon as any ocpp client connects to the server you will see corresponding message in log window. In the communicator tab on the left panel you will see connected client. Click to select that client then you will be able to send a message. I will update docs with the next release. Don't hesitate to ask questions.

**Comment by jpaquete** [comment]
Got it tks!. Ok so my problem is that I can't connect with my existing clients. I will be trying real fast chargers next few days. Have you done any testing with real chargers ? What ocpp versions are supported ? Can you point out any occp client here on GitHub that are working ?. I can give a hand on the project testing. Many Thanks once again.

**Comment by v-bodnar** [comment]
Yes I have tested this app with real charger. You can build client using this library https://github.com/v-bodnar/Java-OCA-OCPP. Currently ocpp 1.6 is used in this app.
