### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by doumelas** [v-bodnar/ocpp-server#3]
Hi
First, thank you for you're great work,
it would be great if you use docker for your project.
simplify the build and testing it with docker

**Comment by v-bodnar** [comment]
Thanks. Yes it would be nice to have. I don't know when I will have time to do this, currently this project has low priority.

**Comment by v-bodnar** [comment]
I have created new branch https://github.com/v-bodnar/ocpp-server/tree/headless
Headless version with dockerfile is there
